# Generated by Django 4.2.2 on 2023-06-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('rua', models.DateTimeField(max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
