# Generated by Django 4.2.2 on 2023-06-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='rua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
