# Generated by Django 4.2.2 on 2023-06-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_local_options_agenda_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Convidados',
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='convidados',
            field=models.ManyToManyField(to='agenda.convidado'),
        ),
    ]
